name: TeleportBow
version: '1.0-SNAPSHOT'
main: me.raoulpcs.teleportbow.TeleportBow
api-version: 1.18
authors: [ raoulpcs ]
description: A magical bow plugin that teleports you and stuff
website: https://youtube.com/KodySimpson
commands:
  givebow:
    description: Geef jezelf een boog.